# Generated by Django 5.0.3 on 2024-07-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_proveedores', '0001_initial'),
        ('servicios_categorias', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('aforo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_categorias.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_proveedores.cliente')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.comuna')),
            ],
        ),
    ]
