# Generated by Django 5.0.3 on 2024-07-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
