# Generated by Django 5.0.3 on 2024-07-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_roles', '0002_alter_usuario_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='es_staff',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='esta_activo',
        ),
    ]
