# Generated by Django 5.0.3 on 2024-07-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_proveedores', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallecotizaciones_clientes', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='detalle_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_ventas_clientes', to='clientes_proveedores.detallecotizacion'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_proveedores.estadocot'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_proveedores.categoria'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_proveedores.extra'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_proveedores', to='clientes_proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_clientes', to='clientes_proveedores.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_ventas_clientes', to='clientes_proveedores.cotizacion'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_proveedores.metodopago'),
        ),
    ]
